name: IPFS

on: [workflow_dispatch]
#on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

#    - uses: aquiladev/ipfs-action@master
#      id: upload
#      with:
#        path: ./
#        service: filebase
#        pinName: 'ipfs-action'
#        filebaseBucket: ${{ secrets.FILEBASE_BUCKET }}
#        filebaseKey: ${{ secrets.FILEBASE_KEY }}
#        filebaseSecret: ${{ secrets.FILEBASE_SECRET }}

#    - uses: aquiladev/ipfs-action@master
#      id: upload2
#      with:
#        path: ./
#        service: pinata
#        pinName: 'otk-data'
#        pinataKey: ${{ secrets.PINATA_KEY }}
#        pinataSecret: ${{ secrets.PINATA_SECRET }}

    - uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
      with:
        pin-name: 'otk-data'
        path: './'
        pinata-api-key: ${{ secrets.PINATA_KEY }}
        pinata-secret-api-key: ${{ secrets.PINATA_SECRET }}
        verbose: false
        remove-old: true
