name: IPFS

on: [push,workflow_dispatch]
#on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: aquiladev/ipfs-action@master
      id: upload
      with:
        path: ./exp
        service: filebase
        pinName: 'otk-data'
        filebaseBucket: ${{ secrets.FILEBASE_BUCKET }}
        filebaseKey: ${{ secrets.FILEBASE_KEY }}
        filebaseSecret: ${{ secrets.FILEBASE_SECRET }}

#    - uses: aquiladev/ipfs-action@master
#      id: upload2
#      with:
#        path: ./
#        service: pinata
#        pinName: 'otk-data'
#        pinataKey: ${{ secrets.PINATA_KEY }}
#        pinataSecret: ${{ secrets.PINATA_SECRET }}

    - uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
      id: upload_
      with:
        pin-name: 'otk-data'
        path: './exp'
        pinata-api-key: ${{ secrets.PINATA_KEY }}
        pinata-secret-api-key: ${{ secrets.PINATA_SECRET }}
        verbose: false
        remove-old: true

# Нужен платный тариф для закрепления по CID
#    - name: IPFS Publish
#      id: IPFS
#      uses: alexanderschau/ipfs-pinning-action@v1.0.0
#      with:
#        path_to_add: './' #Required
#        endpoint: 'https://api.pinata.cloud/psa' #Required
#        access_token: ${{ secrets.PINATA_JWT }} #Required
#        pin_name: 'otk-data' #Optional

    - run: curl -H "Content-Type:application/json" -H "apikey:${{ secrets.FREEDOMAIN_API_KEY }}" -H "domain:${{ secrets.FREEDOMAIN_DOMAIN }}" --data "{\"update\":{\"type\":\"TXT\",\"name\":\"_dnslink.otk-data.publicvm.com.\",\"content\":\"dnslink=/ipfs/${{ steps.upload.outputs.hash }}\",\"ttl\":0,\"overwrite\":true}}" https://api.dnsexit.com/dns/
